### ISSUE TITLE
Adjust test template to Zeebe version 0.2.0

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#434]
Currently the [test template](https://github.com/zeebe-io/zeebe-test-template-java) does not compile with Zeebe 0.2.0

```
[INFO] -------------------------------------------------------------                                                                    
[ERROR] COMPILATION ERROR :       
[INFO] -------------------------------------------------------------                                                                    
[ERROR] /home/menski/github/camunda-tngp/zeebe-test-template-java/src/test/java/io/zeebe/WorkflowTest.java:[58,18] cannot find symbol   
  symbol:   method completeTaskWithoutPayload()                     
  location: variable c of type io.zeebe.client.TasksClient    
```
