### ISSUE TITLE
Adjust java get start to Zeebe version 0.2.0

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#435]
Currently the [java get started](https://github.com/zeebe-io/zeebe-get-started-java-client) does not compile with Zeebe 0.2.0

```
[INFO] -------------------------------------------------------------                                                                    
[ERROR] COMPILATION ERROR :       
[INFO] -------------------------------------------------------------                                                                    
[ERROR] /home/menski/github/camunda-tngp/zeebe-get-started-java-client/src/main/java/io/zeebe/Application.java:[67,27] cannot find symbol
  symbol:   method completeTask(java.lang.String)                   
  location: variable controller of type io.zeebe.client.TasksClient 
```
